### ISSUE TITLE
more support for IO/logging ?

### ISSUE THREAD

**Issue by simonmichael** [kallisti-dev/hs-webdriver#110]
I imagine it is common to want to do IO in WD for troubleshooting or logging. I found these useful (especially before I found the session's browser window, which hides in the back on OSX):

```haskell
p :: Show a => a -> WD ()
p = liftIO . print

printUrl :: WD ()
printUrl = getCurrentURL >>= liftIO . putStrLn

writeScreenshot :: FilePath -> WD ()
writeScreenshot f = screenshot >>= liftIO . B.writeFile f

wait :: Int -> WD ()
wait = liftIO . threadDelay
```

But I wonder if it would be possible to have IO actions just work in WD.

**Comment by kallisti-dev** [comment]
they can't really "just work" unless you define entire libraries containing `liftIO` equivalents of existing IO functions. This is a constraint resulting from a combination of the Haskell type system as well as the base IO libraries not being polymorphic by default. You may be interested in [the lifted-base package](https://hackage.haskell.org/package/lifted-base), which contains lifted polymorphic variants of some common IO functions.
