### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by pavlosgi** [kallisti-dev/hs-webdriver#120]
Can we get a release with the latest?

**Comment by parsonsmatt** [comment]
This would be greatly appreciated @kallisti-dev. 

I have tested the four open PRs in my fork for some integration testing we're doing at work, and they're working for selenium with Chrome. If those can be merged as well that'd be fantastic.

I'm open to helping to maintain this project as well so if you want to add me to the committers, that'd be great.

**Comment by kallisti-dev** [comment]
My apologies for the delay on release. I haven't had as much free time
available for open source dev unfortunately. I'll look at the pull requests
tonight and push a release. I'll also be looking at giving commit access to
interested contributors.

Thank you for your patience.

**Comment by kallisti-dev** [comment]
0.8.5 is on Hackage now. Thanks again for your patience.

**Comment by kallisti-dev** [comment]
Looks like Travis builds are failing for GHC 7.4 and 7.6. Odd considering that all the pull requests passed.
