### ISSUE TITLE
get Session into IO Monad

### ISSUE THREAD

**Issue by dawei-dev** [kallisti-dev/hs-webdriver#128]
Hello I'm trying to run interactively the commands within ghci and I would love to have access to the Session created by runSession. In order to do that a function that returns the Session wrapped in IO is needed. Could you add this feature?

**Comment by parsonsmatt** [comment]
Since `runSession` does not close the session, you can write:

```haskell
main :: IO ()
main = do
    session <- runSession config getSession
    doStuffWith session
```

**Comment by swamp-agr** [comment]
Hi @dawei-dev ,

For me following approach works fine in GHCi:
```
> sess <- runSession chromeConfig  getSession
> elem <- runWD sess $ findElem (ByClass "some-class")
> runWD sess $ click elem
```

Hope it helps!

Best Regards,
Andrey
