### ISSUE TITLE
BadJSON parsing cookie expiry

### ISSUE THREAD

**Issue by dten** [kallisti-dev/hs-webdriver#135]
Recently (not sure when) the expiry time in cookies has sub section precision which causes BadJSON trying to parse it as an `Integer`

e.g. a cookie with  `"expiry":1509022264.455114`
results in `uncaught exception: BadJSON (BadJSON "Floating number specified for Integer: 1.509022264.455114e9")`

https://github.com/kallisti-dev/hs-webdriver/blob/643d6ad02b52fb9dee8d9afec42d895d5f79af78/src/Test/WebDriver/Commands.hs#L356

Currently marked as an `Integer` in the type

Suspect this needs to be either a `Double` or a pair of something (often nanos is separated out)

**Comment by swamp-agr** [comment]
Hi @dten, 

Suggested by you fix works fine for me! I am able to dump and restore cookie data in my tests.

Thanks,
Andrey

**Comment by cvogt** [comment]
Experienced the same issue. Proposed fix looks correct!
