### ISSUE TITLE
Can this module be used to make the browser headless?

### ISSUE THREAD

**Issue by neatville** [kallisti-dev/hs-webdriver#141]
I tried searching, and I can't seem to even find any mention of doing this with Haskell. 
Although, I do wonder if that is possible yet beyond the scope of this module's capabilities. (kind of like you have to start the selenium server outside of Haskell before running the tests). I did find an issue on here about PhantomJS, but I think that has become less relevant in recent years as chromedriver and geckodriver have caught up. 
With Python and selenium I would just specify how everything should be within the python code itself - headless or not, what user agent should I use, etc.

**Comment by kallisti-dev** [comment]
You can pass options to the underlying browser to make it headless.
Different browsers have different options.

**Comment by swamp-agr** [comment]
Hi @neatville ,

Yes, sure! You can specify your ow headless browser, see below:

```
chromeConfig = useBrowser chr defaultConfig { wdHost = "0.0.0.0", wdPort = 4444, wdHTTPRetryCount = 50 }
  {-where chr = chrome
              { chromeBinary = Just "/usr/bin/chromium"
              , chromeOptions = ["--headless"
                                , "--user-agent=\"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.50 Safari/537.36\""
                                , "--mute-audio"
                                , "--disable-gpu"
                                ]
              }

htmlUnitConfig = useBrowser HTMLUnit defaultConfig

phantomConfig = useBrowser phantom defaultConfig
  where phantom = Phantomjs
                    { phantomjsBinary = Just "/opt/phantomjs/bin/phantomjs"
                    , phantomjsOptions = [ "/opt/phantomjs/src/ghostdriver/main.js"
                                         , "--webdriver=8910"
                                         , "--webdriver-selenium-grid-hub=http://127.0.0.1:4444"
                                         , "--webdriver-logfile=/var/log/phantomjsdriver.log"
                                         ]
                    }


```


Thanks,
Andrey
