### ISSUE TITLE
How to run headleass Firefox?

### ISSUE THREAD

**Issue by mnn** [kallisti-dev/hs-webdriver#145]
I found only configs for headless Chrome (#141), but not how to do it with Firefox. I somewhere saw it could be done via passing an environmental variable, but it was a bit old article and also I have no idea how to pass an env. variable to Firefox.

Edit: Found it could be done by passing an argument `-headless`. Not sure if that helps me, I see in Firefox config only field for a path to a binary.

**Comment by mnn** [comment]
Tried using the binary path `ffBinary` with arguments without success.

```
Session: <no session id> at "127.0.0.1":4444
java.lang.IllegalStateException: Specified firefox binary location does not exist or is not a real file: /usr/bin/firefox
 -headless
```

**Comment by swamp-agr** [comment]
Hi @mnn, 

1. Do you have [`geckodriver`](https://github.com/mozilla/geckodriver/releases) installed in your environment?
2. Is it correct firefox location on your system?

Thanks,
Andrey

**Comment by mnn** [comment]
Hello @swamp-agr,

yes, geckodriver is present and working when I don't change `ffBinary`. Location is correct, but if I add the command line argument to `ffBinary`, it breaks, since I guess it doesn't accept arguments this way.

Commented line doesn't work: https://gitlab.com/monnef/redmine-overtime-calculator/blob/2230a46d670d53152fd09e00e516f62547ef1c9c/src/Main.hs#L167

Thanks for your time,
monnef

**Comment by swamp-agr** [comment]
Hi @mnn,

I tried and was able to reproduce this issue. 
After some investigation it was identified that issue caused by missing Firefox capability: `firefox_options`.
Please expect PR that will resolve this issue by this week.

Thanks,
@swamp_agr

**Comment by swamp-agr** [comment]
JFYI:

Issue for `firefox` is still relevant. 
Adding hook `firefox_options` into its capabilities seems does not work.
