### ISSUE TITLE
Release to Hackage

### ISSUE THREAD

**Issue by AlexeyRaga** [kallisti-dev/hs-webdriver#158]
There has been a number of fixes, notably https://github.com/kallisti-dev/hs-webdriver/pull/133

@kallisti-dev can we have a new release on Hackage?

**Comment by kallisti-dev** [comment]
Done! Finally! [webdriver-0.9 has been uploaded to Hackage](https://hackage.haskell.org/package/webdriver-0.9)

Sorry for such a long delay. I will be making a better effort to keep on top of releases in the future.
