### ISSUE TITLE
Cannot get the page opened

### ISSUE THREAD

**Issue by 573** [kallisti-dev/hs-webdriver#69]
I try to automate tests with the help of hs-webdriver, code see below. I have a selenium-server instance started ("Started SocketListener on 0.0.0.0:4444"). Everytime I run the main function in ghci I get an

    *** Exception: TimeoutTriggered

and also the given page isn't opened. Do you have any idea what I'm doing wrong?

    :set -XOverloadedStrings    
    :m + Test.WebDriver Control.Monad Test.WebDriver.Commands.Wait
    let main :: IO() ; main = runSession defaultConfig $ do { openPage "http://stackoverflow.com/questions/ask" ; waitUntil 60 (findElem $ ByXPath ".//div") ; return () }

I also compiled the tests coming with the hs-webdriver now, but running `.\dist\build\test-search-baidu\test-search-baidu.exe` got me a: `test-search-baidu.exe: TimeoutTriggered.`

**Comment by 573** [comment]
On Ubuntu it works. The problem description is Windows only.

**Comment by kallisti-dev** [comment]
Does Firefox launch when you start the session?

**Comment by 573** [comment]
Yes it does launch.

**Comment by kallisti-dev** [comment]
Looks like I get the same problem using hs-webdriver 0.6.1 with selenium 2.45, both in firefox and chrome.

**Comment by 573** [comment]
Seems the issue is located somewhere around what is described [here](http://superuser.com/a/536198/432066). Maybe selenium-server can be configured to start the socketlistener at localhost... instead of 0.0.0.0...

**Comment by kallisti-dev** [comment]
The issue doesn't seem to be with finding the server, since the session is created according to the selenium server logs.

**Comment by kallisti-dev** [comment]
One thing I forgot to mention is that you're not using `withSocketsDo` from the `Network.Socket` module. This is usually necessary in Windows environments to initialize winsock API. That being said, I still get the same `TimeoutTriggered` error despite using `withSocketsDo`

**Comment by kallisti-dev** [comment]
Update: I ran the search-baidu test on Selenium server 2.48.2 and whatever the issue is it appears to be resolved now. I think it's safe to assume this was a problem on the Selenium side and not the Haskell bindings.
