### ISSUE TITLE
FindElems and FindElemsFrom

### ISSUE THREAD

**Issue by AndrewRademacher** [kallisti-dev/hs-webdriver#76]
In commit b11eba5a41f03b3897082e97920b8b201fffa587, the `findElems` and `findElemsFrom` functions no longer return lists of elements, but a single element. What is the motivation for this change, and is there another way to go about getting lists of elements off a page?

**Comment by kallisti-dev** [comment]
No that's actually a mistake that happened somewhere within the latest release cycle. Most likely when I was working with an experimental change to overload list return types to a generic typeclass. I decided against it, but apparently forgot to add the [] back to the types.

I'll go ahead and make a quick bug fix release. There should really be more comprehensive tests to catch these kinds of mistakes. It's actually quite a bit of work to get a comprehensive test suite going for a webdriver client.

**Comment by kallisti-dev** [comment]
0.8.0.1 is on Hackage. Thanks for spotting that mistake!
