### ISSUE TITLE
Webdriver 0.8.0.1 doesn't work with aeson before 0.10

### ISSUE THREAD

**Issue by wuzzeb** [kallisti-dev/hs-webdriver#77]
Compiling with stackage LTS (which uses aeson 0.8 still) results in the compile error

```
src/Test/WebDriver/Commands.hs:216:55:
    Could not deduce (ToJSON (f JSArg)) arising from a use of ‘pair’
    from the context (Foldable f, FromJSON a, WebDriver wd)
      bound by the type signature for
                 executeJS :: (Foldable f, FromJSON a, WebDriver wd) =>
                              f JSArg -> Text -> wd a
      at src/Test/WebDriver/Commands.hs:213:14-78
    In the second argument of ‘(.)’, namely ‘pair ("args", "script")’
    In the expression:
      doSessCommand methodPost "/execute" . pair ("args", "script")
    In the expression:
      doSessCommand methodPost "/execute" . pair ("args", "script")
      $ (a, s)

src/Test/WebDriver/Commands.hs:228:61:
    Could not deduce (ToJSON (f JSArg)) arising from a use of ‘pair’
    from the context (Foldable f, FromJSON a, WebDriver wd)
      bound by the type signature for
                 asyncJS :: (Foldable f, FromJSON a, WebDriver wd) =>
                            f JSArg -> Text -> wd (Maybe a)
      at src/Test/WebDriver/Commands.hs:225:12-84
    In the second argument of ‘(.)’, namely ‘pair ("args", "script")’
    In the expression:
      doSessCommand methodPost "/execute_async" . pair ("args", "script")
    In the expression:
      doSessCommand methodPost "/execute_async" . pair ("args", "script")
      $ (a, s)
```

Doing some investigation, it looks like the instance `(Foldable f, ToJSON a) => ToJSON (f a)` was only added in aeson version 0.10.  The simplest fix is just to call `toList` explicitly.  If I changed `executeJs` and `asyncJs` to call `toList` on the parameter `a`, everything compiles.

**Comment by kallisti-dev** [comment]
I had assumed when I saw that instance in the aeson docks that it had been available for some time. The `toList` fix should be sufficient.

**Comment by kallisti-dev** [comment]
What version of aeson did you build with? It's not important to this fix, but I'd like to know so I can try building with earlier versions to check for build problems.

**Comment by wuzzeb** [comment]
I just kept using stackage lts, so version 0.8.  I used stack plus this stack.yaml to build

```
resolver: lts-3.9
packages:
    - .
```

**Comment by kallisti-dev** [comment]
Ah okay. Do you think I should deprecate 0.8.0.1 on hackage? Based on the assumption that most webdriver builds out there aren't currently built against aeson 0.10?

**Comment by wuzzeb** [comment]
I would just upload 0.8.0.2 with a fix like https://github.com/wuzzeb/hs-webdriver/commit/c9ba1dd5b76730f688eaab0e3c50a481fa428e6c

**Comment by kallisti-dev** [comment]
0.8.0.2 is up. I also deprecated 0.8.0.1 on Hackage because I don't like the idea of a version floating around that breaks on the vast majority of aeson versions listed as valid dependencies.

**Comment by kallisti-dev** [comment]
@wuzzeb  just a heads up: 0.8 through 0.8.0.2 breaks on GHC < 7.10; I pushed 0.8.0.3 to fix those issues.
