### ISSUE TITLE
phantomjs cli args not passed to Ghostdriver/PhantomJS

### ISSUE THREAD

**Issue by agreif** [kallisti-dev/hs-webdriver#81]
with the following config

    myConfig = defaultConfig { wdCapabilities = defaultCaps { browser = Browser "phantomjs",
        acceptSSLCerts = Just True,
        additionalCaps = [("phantomjs.page.settings.userAgent","...")
                                 ,("phantomjs.cli.args", "--webdriver-logfile=/tmp/foo.log --webdriver=11122 --ignore-ssl-errors=yes")
                                 ,("phantomjs.binary.path", "/usr/local/bin/phantomjs")
                                  ]} }

the selenium node does not pass the cli args to the phantomjs process:

    12:12:03.125 INFO - Executing: [new session: Capabilities [{proxy={proxyType=SYSTEM}, acceptSslCerts=true, phantomjs.binary.path=/usr/local/bin/phantomjs, phant
    omjs.page.settings.userAgent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:42.0) Gecko/20100101 Firefox/42.0, browserName=phantomjs, phantomjs.cli.args=--webd
    river-logfile=/tmp/foo.log --webdriver=11122 --ignore-ssl-errors=yes, platform=ANY}]])
    12:12:03.169 INFO - Creating a new session for Capabilities [{proxy={proxyType=SYSTEM}, acceptSslCerts=true, phantomjs.binary.path=/usr/local/bin/phantomjs, phantomjs.page.settings.userAgent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:42.0) Gecko/20100101 Firefox/42.0, browserName=phantomjs, phantomjs.cli.args=--webdriver-logfile=/tmp/foo.log --webdriver=11122 --ignore-ssl-errors=yes, platform=ANY}]
    12:12:03.182 INFO - executable: /usr/local/bin/phantomjs
    12:12:03.182 INFO - port: 38882
    12:12:03.182 INFO - arguments: [--proxy-type=system, --webdriver=38882, --webdriver-logfile=/var/crawler/selenium/phantomjsdriver.log]
    12:12:03.182 INFO - environment: {}
    PhantomJS is launching GhostDriver...
    [INFO  - 2015-12-08T11:12:03.864Z] GhostDriver - Main - running on port 38882
    [INFO  - 2015-12-08T11:12:04.038Z] Session [82d711a0-9d9c-11e5-9a25-558c16c15c60] - page.settings - {"XSSAuditingEnabled":false,"javascriptCanCloseWindows":true
    ,"javascriptCanOpenWindows":true,"javascriptEnabled":true,"loadImages":true,"localToRemoteUrlAccessEnabled":false,"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.

as can be seen in the line "12:12:03.182 INFO - arguments: " the arguments are not the ones from the haskell code.

I am using sleenium node with 'selenium-server-standalone.2.48.2.jar' and phantomjs 1.9.8,
and starting the node like this:

    $JAVA -jar ./selenium-server-standalone.jar \
    -role node \
    -hub http://localhost:4444/grid/register \
    -host localhost \
    -port $PORT \
    -browser "browserName=phantomjs,maxInstances=5" \
    -maxSession 5 \
    -timeout 30000 \
    -nodePolling 5000 \
    -downPollingLimit 3 \
    -unregisterIfStillDownAfter 5000

Any Ideas how to pass command line args to the phantomjs browser?
Do I miss something?

thanks,
Alex.

**Comment by kallisti-dev** [comment]
I'm not very familiar with this particular stack, but I think you might have better results running and connecting to phantomjs directly as the webdriver server, rather than going through the standalone JAR.

**Comment by agreif** [comment]
sure, then I can use the command line options directly.
But the standalone jar is quite convenient, because it can spawn new instances on demand.

ok, I will close this issue,
