### ISSUE TITLE
Click the button with a native JS 

### ISSUE THREAD

**Issue by denisshevchenko** [kallisti-dev/hs-webdriver#83]
Hi!

I need to click some button, but not with a `click` function, but with a native JS. I see a special function for this task, `executeJS`. So this is my code:

```haskell
    ...
    button <- findElement . ById $ "clearCart"
    info <- elemInfo button
    executeJS [JSArg info] "arguments[0].click();"
    ...
```

But I got a runtime error:

```bash
BadJSON "when expecting a (), encountered Null instead"
```

How can I fix it?

**Comment by CristhianMotoche** [comment]
The problem is that your Javascript code doesn't return (). You should return something, for example: 
```
executeJS [JSArg info] "arguments[0].click(); return \"\""
```
And you could use void from control Monad to return ()

**Comment by denisshevchenko** [comment]
Thanks. I've got another variant, from Haskell mailing list:

```haskell
     info <- elemInfo button
     result <- executeJS [JSArg info] "arguments[0].click();"         
     maybe (return ()) return result
```

And it woks just fine with `PhantomJS 2.0.0`. But when I try to use it with `selenium-server-standalone-2.48.2`+`Firefox 42.0`, I got this error:

```bash
BadJSON "when expecting a StackFrame, encountered Null instead"
```

What can I do?

**Comment by denisshevchenko** [comment]
Moreover, I see the same error even if I want just print element's info:

```haskell
        ...
        info <- elemInfo button
        liftIO $ print info
        ...
```

With PhantomJS I see something like this:

```
Object (fromList [("ELEMENT",String "%3Awdc%3A1450441660846")])
```

But with Selenium+Firefox I see the same error:

```
BadJSON "when expecting a StackFrame, encountered Null instead"
```

**Comment by kallisti-dev** [comment]
After some probing, it would appear the issue is that the Selenium server is throwing an UnsupportedCommandException, but the stack trace JSON array is just a list of nulls. So the error parsing on the Haskell-side of things is throwing a BadJSON on those null values, since the `FromJSON StackFrame` instance was never intended to correctly parse null values.

My best guess for why this is happening is that the old elemInfo command has been phased out in the new Marionette driver for Firefox, as part of the migration towards the [new W3C WebDriver spec](http://www.w3.org/TR/webdriver/), but instead of responding with a standard 404 response for unknown commands it's responding with weird stuff.

I added a quick fix to the JSON parsing in 41c8b392763bc389a4886bcf612290a6470dd6c1 so at least you'll see the actual server-side error now.

**Comment by kallisti-dev** [comment]
To summarize: `elemInfo` on the latest Selenium versions (at least when using Firefox) has been deprecated. Perhaps a DEPRECATE pragma is in order?

**Comment by denisshevchenko** [comment]
Ok, I've updated `webdriver` up to `0.8.0.4` and try again:

```haskell
        ...
        info <- elemInfo button
        liftIO $ print info
        ...
```

Now I see this error message:

```bash
'UnknownError': GET /session/e6ec6cd4-7296-4998-9800-b655a9021978/element/1
```

So, what can I do now?..

**Comment by kallisti-dev** [comment]
Yes, as mentioned previously, the `elemInfo` command is no longer supported with Firefox. This is an upstream deprecation in the Marionette project, and nothing I have control over.

**Comment by denisshevchenko** [comment]
Ok, I understand. Thank you.

**Comment by denisshevchenko** [comment]
I found a little bit compromised solution: if we want to click via JS - we should find a button via JS too. For example:

```haskell
clickViaJavaScript :: Text -> WD ()
clickViaJavaScript identifier = do
    executeJS [] (jsClick identifier) :: WD Text
    return ()

jsClick :: Text -> Text
jsClick = 
    "var element = $(\"#" `T.append` anId `T.append`
    "\");if(element.length){element.show().click();return \"Ok\";}else{return \"Fault\";}"
```

And it works perfectly.

**Comment by kallisti-dev** [comment]
As far as I'm aware you can actually just pass an `Elemen~ directly as a `JSArg`, so something like this should work:

```
clickJS :: Element -> WD ()
clickJS e = executeJS [JSArg e] "arguments[0].click();"
```
WebDriver handles this as a special case and will automatically convert the `Element` reference to its relevant DOM object. Likewise, if you return a DOM object it will automatically be converted to an `Element` reference.

**Comment by kallisti-dev** [comment]
Actually I forgot that `noReturn` is an internal function that isn't exported, but it looks like this:

```haskell
import Test.WebDriver.JSON
noReturn :: WebDriver wd => wd NoReturn -> wd ()
noReturn = void
```

This allows you to convince the parser that `Null` and various other "no return" values are okay. I'll probably export it in Test.WebDriver.JSON in next release.

**Comment by kallisti-dev** [comment]
Note: DEPRECATED pragma has been added to `elemInfo` (533575b5bf1302a1e21992a13211265ea52f9e3e) and  `noReturn` is now exported (43cbd3b1b34a56cf22042f3fc829052beaba7253)

**Comment by denisshevchenko** [comment]
Thanks @kallisti-dev for your help!

**Comment by kallisti-dev** [comment]
No problem.
