### ISSUE TITLE
Selenium and PAC proxy: empty path to PAC-file in Firefox

### ISSUE THREAD

**Issue by denisshevchenko** [kallisti-dev/hs-webdriver#84]
Hi again!

I try to use a proxy capability. When I use `Manual` proxy setting - it works like a charm: I see corresponding proxy settings in the Network settings of the Firefox (started by Selenium standalone server). But when I try to use `PAC` proxy, I got a problem.

This is my code:

```haskell
capabilities :: Capabilities
capabilities = defaultCaps { proxy = pacBasedProxy }
  where
    pacBasedProxy = PAC { autoConfigUrl = pathToBrowserPACFileAsURL }
```

Function `pathToBrowserPACFileAsURL` returns a file path to the PAC-file (like `file:///tmp/selenium-pac-test`). File actually exists, its content is correct (I've checked it). But if I look in the Network setting of the Firefox - I see an empty path to the PAC-file:

![alt text](https://i.imgur.com/v5efvoP.png "Test")

As you can see, PAC proxy option is active, but path to the PAC-file is empty... Obviuosly, PAC-based proxy doesn't work in this case...

This is what I see in the Selenium server's log:

```bash
Executing: [new session: Capabilities [{proxy={autoConfigUrl=file:///tmp/selenium-pac-test, proxyType=PAC}, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@27d3164b, browserName=firefox, platform=ANY}]])
```

Selenium *see* that I want to use PAC-based proxy, but why is path to the PAC-file empty? How can I fix it?

**Comment by denisshevchenko** [comment]
I've even tried another PAC-path format (refer on https://code.google.com/p/selenium/wiki/DesiredCapabilities#Proxy_JSON_Object), like this:

```haskell
PAC { autoConfigUrl = "http://hostname.com:1234/pacfile" }
```

But path to PAC-file in Firefox is still empty...

**Comment by denisshevchenko** [comment]
In fact, I need very simple behavior: the only particular requests via proxy and all other requests - directly. I could do it via `Manual` proxy too, but in this case, I need an access to `No Proxy for` option. Unfortunately, I can't find corresponding function in `webdriver`'s modules...

**Comment by denisshevchenko** [comment]
Hm, I think I found a little bug: name of path to PAC-file in http://hackage.haskell.org/package/webdriver-0.8.0.4/docs/src/Test-WebDriver-Capabilities.html#line-623.

```haskell
autoConfigUrl -> proxyAutoconfigUrl
```

Based on https://code.google.com/p/selenium/wiki/JsonWireProtocol#Proxy_JSON_Object.

This is PR: https://github.com/kallisti-dev/hs-webdriver/pull/85.

**Comment by kallisti-dev** [comment]
PR merged.

**Comment by humble-student** [comment]
Sorry to resurrect an old post but how were you able to pass that variable to the remote firefox web driver?  I am having problems doing so.  Here is a code I am playing around with.  Any help and points to the right direction would greatly be appreciated. 

Browser is firefox, server is redhat, proxy is a .pac file

`from selenium import webdriver
from selenium.webdriver.common.proxy import Proxy, ProxyType
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.firefox.options import Options
from multiprocessing.managers import AutoProxy

desired_capabilities = webdriver.DesiredCapabilities.FIREFOX.copy()

PAC_PROXY = {
    'proxyAutoconfigUrl': 'http://pac.com/autoproxy/web-proxy.pac',
}

def testCanAddPACProxyToDesiredCapabilities():
    proxy = Proxy()
    proxy.proxy_autoconfig_url = PAC_PROXY['proxyAutoconfigUrl']

    desired_capabilities = {}
    proxy.add_to_capabilities(desired_capabilities)

    proxy_capabilities = PAC_PROXY.copy()
    proxy_capabilities['proxyType'] = 'PAC'
    expected_capabilities = {'proxy': proxy_capabilities}
    assert expected_capabilities == desired_capabilities

def testCanInitPACProxy():
    proxy = Proxy(raw=PAC_PROXY)
    assert ProxyType.PAC == proxy.proxy_type
    assert PAC_PROXY['proxyAutoconfigUrl'] == proxy.proxy_autoconfig_url
    
    desired_capabilities = {}
    proxy.add_to_capabilities(desired_capabilities)
'''
def testCanInitEmptyProxy():
    proxy = Proxy()
    assert ProxyType.UNSPECIFIED == proxy.proxy_type
    assert proxy.auto_detect is False
    assert '' == proxy.proxy_autoconfig_url
'''    

 
browser = webdriver.Remote( command_executor='http://10.1.1.2:4444/wd/hub', desired_capabilities=desired_capabilities)


browser.get("http://whatismyipaddress.com/")

#print browser.find_element_by_tag_name('body').text
print (browser.find_element_by_tag_name('body').text)

bodyText = browser.find_element_by_tag_name('body').text

print (bodyText)

#WebElement bodyText = broswer.findElement(By.tagName("body"));

if 'Hello' in bodyText:
    print ('Found hello in body')
else:
    print ('Hello not found in body')

browser.quit()








#chrome.get("http://whatismyipaddress.com")`
