### ISSUE TITLE
Hello World command order

### ISSUE THREAD

**Issue by sgronblo** [kallisti-dev/hs-webdriver#86]
https://github.com/kallisti-dev/hs-webdriver/blob/master/examples/readme-example-beginner.md#hello-world shouldn't the example for google here evaluate `sendKeys "Hello, World!" searchInput` before `submit searchInput`?

**Comment by beerendlauwers** [comment]
I've provided a pull request for this: #87 .

**Comment by kallisti-dev** [comment]
Merged.
