### ISSUE TITLE
Add definitions for keys?

### ISSUE THREAD

**Issue by neongreen** [kallisti-dev/hs-webdriver#97]
I have the following definitions:

```
backspace, enter, escape :: Text
(backspace, enter, escape) = ("\xE003", "\xE007", "\xE00C")

shift, control, alt, command :: Text
(shift, control, alt, command) = ("\xE008", "\xE009", "\xE00A", "\xE03D")
...
```

It'd be useful to have a `.Keys` module (designed to be imported qualified) providing said definitions, to allow something like this:

```
    sendKeys ("Some category" <> K.enter) =<< select ".add-category"
```

I can think of several alternatives to this:
  * the definitions might be called like `enter_` and then there'd be no need for qualified imports
  * there might be a `sendKeys'` function handling input of the form `foo{enter}bar{shift}` (or something like that)
  * both things at once

If you want, I will make a pull request.

(Also, the link in the description of `sendKeys` is broken.)

**Comment by CristhianMotoche** [comment]
What keys should be added?

**Comment by CristhianMotoche** [comment]
Let's create a list:

- backspace_ = "\xE003"
- enter_ = "\xE007"
- escape_ = "\xE00C"
- shift_ = "\xE008"
- control_ = "\xE009"
- alt_ = "\xE00A"
- command_ = "\xE03D"

**Comment by neongreen** [comment]
Well, apart from those that I mentioned, I guess that the following would be good:

```
F1              \uE031
F2              \uE032
F3              \uE033
F4              \uE034
F5              \uE035
F6              \uE036
F7              \uE037
F8              \uE038
F9              \uE039
F10             \uE03A
F11             \uE03B
F12             \uE03C
```

And also these:

```
PAGE_UP         \uE00E
PAGE_DOWN       \uE00F
END             \uE010
HOME            \uE011
ARROW_LEFT      \uE012
ARROW_UP        \uE013
ARROW_RIGHT     \uE014
ARROW_DOWN      \uE015
INSERT          \uE016
DELETE          \uE017
```

These are questionable, but in theory a site *could* distinguish between a `0` and a numpad `0`, for instance:

```
SEMICOLON       \uE018
EQUALS          \uE019
NUMPAD0         \uE01A
NUMPAD1         \uE01B
NUMPAD2         \uE01C
NUMPAD3         \uE01D
NUMPAD4         \uE01E
NUMPAD5         \uE01F
NUMPAD6         \uE020
NUMPAD7         \uE021
NUMPAD8         \uE022
NUMPAD9         \uE023
MULTIPLY        \uE024
ADD             \uE025
SEPARATOR       \uE026
SUBTRACT        \uE027
DECIMAL         \uE028
DIVIDE          \uE029
RETURN          \uE006
```

I don't have `null` or `cancel` or `help` keys on my keyboard and I've no idea whether they exist:

```
NULL            \uE000
CANCEL          \uE001
HELP            \uE002
CLEAR           \uE005
```

I haven't checked whether there's any difference between `\t` and `TAB`, or between Alt and Meta:

```
TAB             \uE004
META            \uE03D
```

ZENKAKU_HANKAKU is legitimate but rare:

```
ZENKAKU_HANKAKU \uE040
```

And I don't know about these:

```
PAUSE           \uE00B
SPACE           \uE00D
```

I would propose adding them *all* because there's probably no reason not to add something that Selenium supports (likely for a good reason).

**Comment by CristhianMotoche** [comment]
[Python keys](http://seleniumhq.github.io/selenium/docs/api/py/webdriver/selenium.webdriver.common.keys.html?highlight=keys) for reference

**Comment by CristhianMotoche** [comment]
@neongreen  Could you please explain the function `sendKey'` that you mentioned?

(The link in `sendKeys` [description is working](https://github.com/seleniumhq/selenium-google-code-issue-archive#/session/:sessionId/element/:id/value)).

**Comment by neongreen** [comment]
@CristhianMotoche The link opens a nearly empty README page for me. Luckily, archive.org has the original link archived: <https://web.archive.org/web/20160115155656/https://code.google.com/p/selenium/wiki/JsonWireProtocol#/session/:sessionId/element/:id/value>.

The `sendKeys'` function would take a string, replace `{enter}`, `{up}`, etc. with corresponding escape characters, and send the result with `sendKeys`.

**Comment by CristhianMotoche** [comment]
Oh, I see. The [old link](https://code.google.com/p/selenium/wiki/JsonWireProtocol#/session/:sessionId/element/:id/value) should be change for [this link](https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidelementidvalue). IMO

I got your point about `sendKeys'` function. If you don't mind I'd like to work on this issue.

**Comment by neongreen** [comment]
I noticed that none of the keys are actually reserved identifiers, so it should be possible to have key names without underscores (if we decide that a qualified import is the way to go).

**Comment by kallisti-dev** [comment]
Hey.  Sorry for the delay as I'm currently out of country and only have
mobile available to me.

I do think that qualified import is probably the way to go for this.
Something like Test.Webdriver.Commands.Keys perhaps?

In fact the entire Commands module should be broken up into submodules but
that's a separate issue.

**Comment by kallisti-dev** [comment]
Can you remove the underscores from your branch and then submit a pull request?

**Comment by CristhianMotoche** [comment]
Sure. However, I haven't done the `sendKeys'` function that @neongreen mentioned.

**Comment by kallisti-dev** [comment]
I think the `sendKeys'` concept is something that can be implemented using existing Template Haskell string interpolation tools alongside the newly added key definitions. That being said, I'd be open to adding some sort of TH macro to handle this.

**Comment by kallisti-dev** [comment]
Some examples:
* [interpolate](https://hackage.haskell.org/package/interpolate-0.1.0/docs/Data-String-Interpolate.html)
* [interpolation](https://hackage.haskell.org/package/Interpolation-0.3.0/docs/Data-String-Interpolation.html)
* [interpolatedstring-perl6](https://hackage.haskell.org/package/interpolatedstring-perl6-1.0.0/docs/Text-InterpolatedString-Perl6.html)

They're all pretty similar. Not sure what the pros and cons of each are.

**Comment by kallisti-dev** [comment]
I'm closing this issue as the primary feature of the topic has been added. Feel free to open a new issue for the `sendKeys'` feature, though I would recommend renaming it to something more descriptive (and creating it as a TH macro).
